spring:
    datasource:
        master:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/core?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
            username: root
            password: root
            max-lifetime: 3600000
            minimum-idle: 2
            connection-test-query: SELECT 1
            read-only: false
        slave:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/core?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
            username: root
            password: root
            max-lifetime: 3600000
            minimum-idle: 2
            connection-test-query: SELECT 1
            read-only: true
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: im-group
            auto-offset-reset: earliest
            enable-auto-commit: false
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            fetch-max-wait: 100
            fetch-min-size: 1
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        listener:
            concurrency: 30
    redis:
        host: localhost
        port: 6379
        password:
        timeout: 10000
        jedis:
            pool:
                max-idle: 8
                min-idle: 0
                max-active: 300
                max-wait: -1
#自定义前端url
chat-manager-uri:
    #手机端地址
    chatAdminMbUri: http://chatroom.chatcpk3.club:8098/#/login
    #PC端地址
    chatAdminPcUri: http://chatroom.chatcpk3.club:8098/#/login
#自定义前端aes-key
chat-manager-aes:
    chatAesKey: 1234567887654321



